management:
  endpoints:
    web:
      exposure:
        include: beans, conditions, configprops, env, health, httpexchanges, info, loggers, metrics, mappings, threaddump, shutdown
      base-path: /device-control-server/manage
  endpoint:
    health:
      show-details: always